{% set name = "nb_black" %}
{% set version = "1.0.7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ca52e3a46675f6a0a6d79ac73a1f8f951bef60f919eced56173e76ab1b6d62b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - black
    - ipython

test:
  imports:
    - lab_black
    - nb_black

about:
  home: https://github.com/dnanhkhoa/nb_black
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple extension for Jupyter Notebook and Jupyter Lab to beautify Python code automatically using Black.

extra:
  recipe-maintainers:
    - xhochy
