travis:
  secure:
    BINSTAR_TOKEN: NNbw0cUqypRTBD2GSYVAWVW2PxKBwkFAO1uO+bBZ088AIkQ+CC+BAhz4LucqALq7krWEawAF4ZPjAOMR7v4GFwdAbNB+MG3023s3uR4I4I8+s3wHtN+dIsXwD5YDjkL1Uz0yqgxeROh77fbMNsR79PjlPdDZpdqTprEcVTBN/nvEssB/4fUk85aeETIfIrxo+z7zxAtI0qvdwhgXFcm+xR40idDO1c5zDEN8v8xNpj5Dgq7R5w452gVWEFzxoBe4u1kqUcSOsk/juzWrrEojisWoVoOg0mRDdEC67Hl8QyoTJUzlfs3p7+iem7xHnZhHQXC5FbE1kC7t2yFEW2pT0x+fc8qippMPrGte53/27czocp/7CnhGKjay7CtRFvbwaTMErWOuCvejwfL/0xv6NgMTSNugdzaMDM4QOiHC/pDPg1tMc5/qpNKv3+PwhA0HAopMPDqZaL/Yu1/90SfLnK53iYRa+Etvaja6s5N9sjQLSI97dCD5VJaWnQ543e92SXrT5YvajNCXcYY+F/10xM0+iyCS9l/bj3C581uN7ps8tceqAGpDSFZRuOgqf9mBRAjiw8ubg2FkwrzYVnmJDR1+vaQz5AP4JdB3iFgfH1SD6cWsbf/ZHkp03R/LeTl/Sb+DpumF/+r7EYSN3HIVX8tOSvvhvSaRtEnlXeEJrx8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
